### PR TITLE
add tuple

### PR DESCRIPTION
**Pull request by Hunam6**

### CODE REVIEW

**Comment by JalonSolov** [comment]
Not sure I agree with all your conclusions.  For example, a tuple will _always_ have multiple values.  Just because you can reference only one of them easier (without using `_` to ignore one or more), doesn't mean you won't have extra memory being used.

**Comment by elimisteve** [comment]
I'm not sure if tuples are worth adding, but assuming they are, here are some thoughts on this proposal:

I think `tuple('hello', 42, true)` might be better syntax so it's more explicit, easier to parse, arguably easier to read (though more verbose), and to solve the ambiguity in the function signature `fn() (string, int, bool)`, which syntactically conflates the returning of 3 values and the returning of 1 value that is a tuple.

Implementation-wise, it seems to me that tuples should be syntactic sugar for anonymous structs, which were just added to the language. Thus,

```v
tup := tuple('hello', 42, true)
println(tup[1])
```

could be shorthand for

```v
tup := struct { f0 string; f1 int; f2 bool }{'hello', 42, true}
println(tup.f1)
```

**Comment by elimisteve** [comment]
Maybe tuple field accessing syntax should be `tup.1` rather than `tup[1]`, since the former looks more like accessing a field (which it is) whereas the latter looks like accessing the second member of an array (which it isn't).

**Comment by medvednikov** [comment]
Tuples will never be added.


`x,y,z := foo()` is enough

**Comment by elimisteve** [comment]
> I think `tuple('hello', 42, true)` might be better syntax so it's more explicit, easier to parse, arguably easier to read (though more verbose), and to solve the ambiguity in the function signature `fn() (string, int, bool)`, which syntactically conflates the returning of 3 values and the returning of 1 value that is a tuple.

Another advantage of this syntax: creating a tuple with just one member is no longer syntactically ambiguous. And if we need to do `tuple('hello')` rather than `('hello')` to resolve this ambiguity anyway, then only letting people creating tuples with the `tuple(...)` syntax conforms better to V's One Way philosophy.

**Comment by dumblob** [comment]
Yep, and couple of months later a new RFC will emerge asking for support for named fields in tuples (been there, done that - see Python etc.).

Basically *V* needs an all-encompassing *Grand Unified Struct* (GUS :wink:) supporting all this:
1. up-front definition with a name
2. anonymous inline definition (i.e. local "non-up-front" definition)
3. supporting named fields (i.e. access by position like array)
4. supporting unnamed fields (i.e. access by label like C struct)

Note (3) and (3) has to be supported simultaneously in one struct!

This way we avoid any tuples per se but provide their functionality through glorified structs :wink:.

Side benefit: In theory once implemented, it could be used "as is" to implement [proper keyword arguments](https://github.com/vlang/v/pull/11135#issuecomment-924741620 ) (at least as a "fast enough" temporary solution with looks-like works-like traits).

**Comment by chipnetics** [comment]
Personally, is where I believe tuples will really come in handy is as keys to maps. And would love to see this added as I am a map junky for data analytics.

```
tup := tuple('hello', 42, true)
a_map[tup] = "tuples for all"
```

This will avoid having to do something like `map[string]map[int]map[bool]` to achieve a similar result.

Also, although I'd probably never use the below example, I've seen another language use it as a way to call functions.

```
function signature---> foo(param1 string, param2 int, param3 bool)
Call with tuple---> foo(tup)
```

**Comment by JalonSolov** [comment]
You can do all of that if maps allow structs as keys.

**Comment by ken0x0a** [comment]
I think those multiple value tuple is unlikely to have all same values.

> ```
> tup := tuple('hello', 42, true)
> a_map[tup] = "tuples for all"
> ```

If this expect to use same tuple instance, we can do that already with 

```v
a_map[voidptr(&instance)] // may not need `voidptr` wrap
```

**Comment by Hunam6** [comment]
Thank you all for your feedbacks, I get your disagreement with the "Multiple return values functions" part.
Can I have feedback on the "Variadic functions" part? If we do not add tuples, can this type of thing be possible (`fn foo(args ...) {}`)? In not what other alternatives do your propose?

**Comment by elimisteve** [comment]
@Hunam6 V already supports accepting a variable number of arguments to a function: https://github.com/vlang/v/blob/master/doc/docs.md#variable-number-of-arguments

If you want to accept a variable number of arguments of any type, I think this theoretically works:

```v
fn foo(args ...any) {

}
```

**Comment by JalonSolov** [comment]
... once `any` works correctly.

Personally, I'm not convinced it is a good thing.  It means you'll have a whole lot of "if x is int else if x is string else if..." type code to handle things.

Then again, it's a whole lot like generics, only possibly less total code in the final executable, since it won't create a separate function for each type used.

**Comment by dumblob** [comment]
>If we do not add tuples, can this type of thing be possible (`fn foo(args ...) {}`)? In not what other alternatives do your propose?

As I noted above - variadic functions with arguments of different types would be supported "out of the box" if `struct`s get sligtly improved as I suggested above in https://github.com/vlang/rfcs/pull/26#issuecomment-1182454498 .

@Hunam6 does that sound to your ears as a good and most natural alternative to your proposal solving IMHO all the weaknesses mentioned in this thread?

**Comment by Hunam6** [comment]
### for variadic functions

I don't know how `any` would be implemented, but I imagine a surplus of information to make it work.
**If** this is true and the surplus a bit significant, an array of `any` would be even more significant. Consequently, having a series of individual types seems more efficient.

### for Grand Unified Struct

I have to admit I do not really understand what your suggest, can you give the syntax of each of your bullet points maybe?

**Comment by ken0x0a** [comment]
```v
fn C.msg(args ...any) // this required for objc `objc_msgSend(id, id, id ....)`
```
This used to work fine before, but doesn't work now... 😭

I hope V to have strict syntax, and only one way.
But as V will interoperate with C, Go, &..., there should be a way to bypass those "ONLY FOR" compatibility with other language.

Sorry, it's not about `tuple`.

Can we close this, if "Tuples will never be added."?

**Pull request closed without merging**
